name: Build & Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22222
          script: |
            mkdir -p "${{ secrets.SERVER_APP_DIR }}" && cd $_ 
            if [ ! -d .git ]; then
              git clone --depth 1 --branch main "${{ secrets.REPO_SSH_URL }}" .
            else
              git fetch origin && git reset --hard origin/main
            fi
            docker compose pull --ignore-pull-failures || true
            docker compose down
            docker compose up --build -d --remove-orphans
