name: Build & Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print debug info
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          echo "User: ${{ secrets.SERVER_USER }}"
          echo "App Dir: ${{ secrets.SERVER_APP_DIR }}"
          echo "Repo: ${{ secrets.REPO_SSH_URL }}"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts

          # Add your server to known hosts
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

          # Load private key securely
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}")      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=yes "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            cd "${{ secrets.SERVER_APP_DIR }}"
            if [ ! -d .git ]; then
              git clone --depth 1 --branch main "${{ secrets.REPO_SSH_URL }}" .
            else
              git fetch origin && git reset --hard origin/main
            fi
            docker compose pull --ignore-pull-failures || true
            docker compose build
            docker compose up -d --remove-orphans
          EOF
