name: Build & Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_HOST }} -p 22222 -l ${{ secrets.SERVER_USER }}" << 'EOF'
            cd "${{ secrets.SERVER_APP_DIR }}"
            if [ ! -d .git ]; then
              git clone --depth 1 --branch main "${{ secrets.REPO_SSH_URL }}" .
            else
              git fetch origin && git reset --hard origin/main
            fi
            docker compose pull --ignore-pull-failures || true
            docker compose build
            docker compose up -d --remove-orphans
          EOF
